apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
spec:
  containers:
    - name: apache-container
      image: subhash1010/apache_ka_code
      ports:
        - containerPort: 80
  imagePullSecrets:
    - name: privatekey

